### ISSUE TITLE
Add newer proton version

### ISSUE THREAD

**Issue by imbev** [fastrizwaan/winepak32#2]
It would be useful to have a build for a newer proton version such as what is located at https://github.com/fastrizwaan/flatpak-wine/tree/main/io.github.fastrizwaan.flatpak-proton

Documentation on creating a new winepak runner would also be useful.

**Comment by fastrizwaan** [comment]
Hi, sure, will try to update winepak with the latest versions. 

The problem with winepak is that it takes forever to create a flatpak game bundle (due to compression). Whereas WineZGUI 0.84 (part of flatpak-wine/flatpak-proton) has a "Create Bundle" feature in Backup, after creating a prefix. It is faster because it uses zstd with threads (-T4), bundles game and prefix together. It can be loaded with flatpak-wine / flatpak-proton or system winezgui for flatpak-winezgui. So, it is more portable too.

try: https://github.com/fastrizwaan/flatpak-wine/releases/tag/0.84

**Comment by fastrizwaan** [comment]
Added proton-ge-7.29, wine7 and wine5.

**Comment by fastrizwaan** [comment]
> Documentation on creating a new winepak runner would also be useful.

what runner would u like to use? Playonlinux's? simply see this code https://github.com/fastrizwaan/winepak-x86_64/blob/main/make_winepak-x86_64.sh#L91-L149

**Comment by imbev** [comment]
Thank you.

So you recommend using WineZGUI instead of Winepak?

Not a specific runner, but for creating updated runners on my own or non-added runners.

**Comment by fastrizwaan** [comment]
if you want to add a custom runner say wine-4.0, copy all the files inside wine/ to winepak/runners/ directory.

simply just copy the runner's wine/*  inside runners directory as wine-4.0 (subdir of runners/ directory)
 `make-winepak-x86_64.sh --runner=wine-4.0 -n="my game" -d="./my_game_dir" -e="mygame.exe"`

Yes, the reason is simple, winepak which is based on flatpak-linux (which someone else created) is extremely time consuming both while creating the bundle and installing the bundle, that's the issue with flatpak build-bundle. The time consumption increases with the size of bundle. Whereas winezgui takes only few minutes to create bundle, as it does not use flatpak build-bundle, instead just tar --zstd . (based on compression level used, even at max 19 compression it is 5 times faster than winepak/flatpak-build-bundle which perhaps uses .xz compression which is very slow) 

Winepak is flatpak bundle file with wine+game+script
WineZGUI is game+script which uses flatpak-wine or system wine. If we use flatpak-wine, then it is equal to wine+game+script.

I'll try to get  winepak functionality (wine+game+script) in a flatpak bundle.

Thank you.

**Comment by imbev** [comment]
Thank you
